install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("httr")
install.packages("shinydashboard")
install.packages("leaflet")
install.packages("BiocManager")
install.packages("DESeq2")
install.packages("pheatmap")
