install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("httr")
install.packages("shinydashboard")
install.packages("leaflet")
#install.packages("BiocManager") binder uses R3.4.4 so cannot use these installs
#install.packages("DESeq2")
install.packages("pheatmap")
source("https://bioconductor.org/biocLite.R")
biocLite("DESeq2")
